module.exports = {
  id: {
    type: "string",
    primary: true,
    unique: true,
  },
  Username: {
    type: "string",
    unique: true,
  },
  FirstName: "string",
  LastName: "string",
  Country: "string",
  IsActive: {
    type: "boolean",
    default: true,
  },
  CreatedBy: "int",
  CreateDate: {
    type: "string",
    default: () => new Date().toString(),
  },
  Rate: {
    type: "float",
    default: 0,
  },
  DateOfBirth: "string",
  Gender: "string",
  Work: "string",
  Bio: "string",
  ImageUrl: "string",
  LastTimeOnline: "string",
  chat_with_AI: {
    type: "relationship",
    target: "AIChat",
    relationship: "CHAT_WITH_AI",
    direction: "out",
    eager: true,
  },
  has_a_skill: {
    type: "relationship",
    target: "Skill",
    relationship: "HAS_A_SKILL",
    direction: "out",
    eager: true,
  },
  learn_a: {
    type: "relationship",
    target: "Education",
    relationship: "LEARN_A",
    direction: "out",
    eager: true,
  },
  has_a_social_media: {
    type: "relationship",
    target: "SocialMediaLink",
    relationship: "HAS_A_SOCIAL_MEDIA",
    direction: "out",
    eager: true,
  },
  chat_with: {
    type: "relationship",
    target: "Chat",
    relationship: "CHAT_WITH",
    direction: "out",
    eager: true,
  },
  friend_to: {
    type: "relationship",
    target: "User",
    relationship: "FRIEND_TO",
    direction: "out",
    eager: true,
  },
  contact_us: {
    type: "relationship",
    target: "ContactMessage",
    relationship: "CONTACT_US",
    direction: "out",
    eager: true,
  },
  apply_to: {
    type: "relationship",
    target: "PositionPost",
    relationship: "APPLY_TO",
    direction: "out",
    eager: true,
  },
  write_comment: {
    type: "relationship",
    target: "Comment",
    relationship: "WRITE_COMMENT",
    direction: "out",
    eager: true,
  },
  has_a_task: {
    type: "relationship",
    target: "Task",
    relationship: "HAS_A_TASK",
    direction: "out",
    eager: true,
  },
  in_team: {
    type: "relationship",
    target: "Team",
    relationship: "IN_TEAM",
    direction: "out",
    eager: true,
  },
  send_message: {
    type: "relationship",
    target: "Message",
    relationship: "SEND_MESSAGE",
    direction: "out",
    eager: true,
  },
  leader_in: {
    type: "relationship",
    target: "Team",
    relationship: "LEADER_IN",
    direction: "out",
    eager: true,
  },
  create_task: {
    type: "relationship",
    target: "Task",
    relationship: "CREATE_TASK",
    direction: "out",
    eager: true,
  },
  admin_of: {
    type: "relationship",
    target: "Company",
    relationship: "ADMIN_OF",
    direction: "out",
    eager: true,
  },
  work_on: {
    type: "relationship",
    target: "Project",
    relationship: "WORK_ON",
    direction: "out",
    eager: true,
  },
  rated: {
    type: "relationship",
    target: "Company",
    relationship: "RATED",
    direction: "out",
    eager: true,
  },
};
